version: '3.9'

services:
  producscan:
    image: iotdepartment/producscan:latest
    container_name: producscan
    ports:
      - "10000:8080"   # Expones el puerto 8080 del contenedor en el 10000 del servidor
    environment:
      - ConnectionStrings__DefaultConnection=Server=10.195.10.166,1433;Database=ScanSystemDB;User Id=manu; Password=2022.Tgram2;TrustServerCertificate=True;
    restart: always